name: Docker Image CI

permissions:
  contents: write

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Build the Docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: docker build . --file Dockerfile -t ondratu/bitbeam

      - name: Run build process in Docker
        if: startsWith(github.ref, 'refs/tags/')
        run: docker run --rm -e VERSION=${GITHUB_REF_NAME}
             -w "$GITHUB_WORKSPACE"
             -v "$GITHUB_WORKSPACE:$GITHUB_WORKSPACE" ondratu/bitbeam

      - name: Create release files
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: docker run --rm -e VERSION=${GITHUB_REF_NAME}
             -w "$GITHUB_WORKSPACE"
             -v "$GITHUB_WORKSPACE:$GITHUB_WORKSPACE"
             --entrypoint ''
              ondratu/bitbeam make release

      - name: Create release Changelog
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "# Changes" > RELEASE.txt
          git log --pretty="- %s" $(git describe --tags --abbrev=0 @^)..@ >> RELEASE.txt

      - name: Upload a Build Artifact
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-artifact@v4.6.0
        with:
          name: Output
          path: |
            RELEASE.txt
            bitbeam-stl-${{ github.ref_name }}.zip
            bitbeam-parts-${{ github.ref_name }}.zip
            bitbeam-catalog-${{ github.ref_name }}.zip

      - name: Release a Build Artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          body_path: RELEASE.txt
          files: |
            bitbeam-stl-${{ github.ref_name }}.zip
            bitbeam-parts-${{ github.ref_name }}.zip
            bitbeam-catalog-${{ github.ref_name }}.zip
